### ISSUE TITLE
Wrong instructions for employees

### ISSUE THREAD

**Issue by jamesward** [salesforce/dr-cla#10]
> Thanks for the contribution! Unfortunately we can't verify if the committer, ********, has signed the CLA because they have not associated their commits with their GitHub user. Please follow these instructions to associate your commits with your GitHub user. Then sign the Salesforce Contributor License Agreement and this Pull Request will be revalidated.

Employees do not need to sign the CLA.

**Comment by jamesward** [comment]
We could have a configurable org email suffix that we use to check the commits and provide additional info on the PR and on the CLA signing page.  If `EMPLOYEE_EMAIL_SUFFIX` is set to `foo.com` and the PR contains commits with emails ending in `foo.com` then we change the PR comment to something like:
> It looks like you are an employee and thus don't need to sign the CLA but there is something we need you to do to validate you.  We've emailed you instructions.

The email would provide info on how the employee can be added to the org to avoid the CLA check.  The reason for the email instead of providing the instructions via the comment is that the instructions probably have to contain internal info that shouldn't be public.

**Comment by jamesward** [comment]
Note that I think we'll have to only show this once the commits contain a GitHub associated email because we don't want to send emails to unverified email addresses.

**Comment by fernomac** [comment]
Yeah, I like this approach.

**Comment by jamesward** [comment]
https://developer.github.com/v3/repos/commits/#get-a-single-commit

So essentially, if `commit.author.email` ends with `@foo.com` and `author` is defined then no CLA needed.  This assumes that GitHub requires the email to be verified before linking an email to an account.

**Comment by jamesward** [comment]
Looks like it does fill in the `author` as soon as it is added but does indicate that the email is unverified:
https://api.github.com/repos/jamesward/asdf/commits

`commit.verification.reason == "unverified_email"`

**Comment by amateurhuman** [comment]
In order to be verified, the commit needs to both have a verified email and be signed. Pure conjecture, but I'm guessing most people aren't signing their commits (e.g., [argus not verified commit](https://api.github.com/repos/salesforce/argus/commits/17406da16f49b692dd8fee099cb4463f3eb6d022) below). So you can reduce the false positives by whitelisting a domain and auto-accepting verified commits but it won't catch all.

I'd probably focus on something utilizing the `committer` object the comes along with commits. The whitelist could be stored as a file of whitelisted github usernames or call an API that verifies first (technically we should rely on github id since usernames can change but IDs are permanent). 

````
{
  "sha": "17406da16f49b692dd8fee099cb4463f3eb6d022",
  "commit": {
    "author": {
      "name": "Dilip",
      "email": "ddevaraj@salesforce.com",
      "date": "2018-04-21T04:59:33Z"
    },
    "committer": {
      "name": "Dilip",
      "email": "ddevaraj@salesforce.com",
      "date": "2018-04-21T04:59:33Z"
    },
    "message": "Add qurey window and no. expanded time series as attributes from metric reader back to perffilter",
    "tree": {
      "sha": "d398e783dc88eb199560a55f4e77c53b2b778da6",
      "url": "https://api.github.com/repos/salesforce/Argus/git/trees/d398e783dc88eb199560a55f4e77c53b2b778da6"
    },
    "url": "https://api.github.com/repos/salesforce/Argus/git/commits/17406da16f49b692dd8fee099cb4463f3eb6d022",
    "comment_count": 0,
    "verification": {
      "verified": false,
      "reason": "unsigned",
      "signature": null,
      "payload": null
    }
  },
````

**Comment by jamesward** [comment]
Oh bummer.  If the commit isn't signed then we don't get `commit.verification.reason == "unverified_email"`.  So it won't work to rely on GitHub for verifying the email.
