### ISSUE TITLE
Make this project more generic

### ISSUE THREAD

**Issue by jamesward** [salesforce/dr-cla#16]
The name, provided CLA, and favicon are Salesforce specific.

**Comment by DarthHater** [comment]
I'm going to need to do a lot of this to get it working for @sonatype , I can probably float a PR as I do. Do you prefer that the paths, etc... are in Environment variables?

**Comment by jamesward** [comment]
We can use the Typesafe Config system to setup a hierarchy of places to find values.  Because some of the stuff that needs to be agnostic is files, we'll have to figure out what makes sense for different deployment environments.  I do git-based deploys on Heroku, so all the files need to be in the git repo or externalized somewhere.  That makes it a little bit tricky.
