### ISSUE TITLE
Obfuscate Emails

### ISSUE THREAD

**Issue by jamesward** [salesforce/dr-cla#27]
When commits aren't associated with GitHub users the committer's email is displayed in the CLA comment.  Obfuscate that email to avoid spam via scraping.

**Comment by afalko** [comment]
We should probably also edit all the previous comment to remove emails from there.

**Comment by jamesward** [comment]
Reopened to address @afalko's comment.

**Comment by jamesward** [comment]
I've gone through the comments made by the bot (the ones I could find) and removed the emails.
