### ISSUE TITLE
App exception accessing CLA status page

### ISSUE THREAD

**Issue by edmorley** [salesforce/dr-cla#36]
Hi!

On https://github.com/salesforce/oss-template/pull/7 the GitHub status check links to the URL:
https://cla.salesforce.com/status/salesforce/oss-template/pull/7

Visiting that page I get:

> Oops, an error occurred
> This exception has been logged with id 7jfd8pbb8.

**Comment by jamesward** [comment]
Not sure what is going wrong and I no longer have access to manage that app.  BTW, Sonatype created a new version of Dr CLA written in Go: https://github.com/sonatype-nexus-community/the-cla  Maybe Salesforce could switch to something that is actively maintained.
