### ISSUE TITLE
how to force all users even internal organization users to sign CLA ? 

### ISSUE THREAD

**Issue by vagharsh** [salesforce/dr-cla#37]
how can i force internal and external users to sign CLA ?

**Comment by jamesward** [comment]
Typically employees do not need to sign a CLA because their employment agreement covers ownership of what they produce. 
 But if you need that for some reason, you'd have to modify the code.  However you might want to investigate other CLA tool options since I'm no longer working on this one.

**Comment by vagharsh** [comment]
ok thanks ..
