### ISSUE TITLE
connect cla to external webhook

### ISSUE THREAD

**Issue by vagharsh** [salesforce/dr-cla#38]
is there a way to trigger an external webhook when someone signs a CLA successfully ?

**Comment by jamesward** [comment]
Not currently. But that could be added.

**Comment by vagharsh** [comment]
is there an estimation on this ? where can i follow updates ?

**Comment by jamesward** [comment]
this project isn't really maintained anymore.  A more maintained conceptual fork of this project is at: https://github.com/sonatype-nexus-community/the-cla

**Comment by vagharsh** [comment]
oh nice thanks... let me check that one out .. i will ask the same question there in case someone knows about an external webhook
